- name: Upload all tar-backup to Google drive using Restic
  hosts: akira-home
  become: yes
  vars:
   RESTIC_HOME_DIR: "/root/restic"
  tasks:
   - name: Make sure script is present
     ansible.builtin.copy:
      src: files/background-job.sh
      mode: 600
      dest: "{{RESTIC_HOME_DIR}}/background-job.sh"
   - name: Crontab to run backup at 1:30 AM
     ansible.builtin.cron:
      name: Upload to cloud cronjob
      hour: 1
      minute: 30
      job: "{{RESTIC_HOME_DIR}}/background-job.sh >> {{RESTIC_HOME_DIR}}/info.log 2>> {{RESTIC_HOME_DIR}}/error.log"