- name: Manage Prometheus
  hosts: ubuntu-server
  become: yes
  vars:
   uid: 65534
   prometheus_home_dir: /mnt/data2/prometheus
   prometheus_config_dir: "{{prometheus_home_dir}}/etc"
   prometheus_data_dir: "{{prometheus_home_dir}}/data"
  pre_tasks:
   - name:  Create Prometheus data and config exists
     ansible.builtin.file:
      path: "{{prometheus_home_dir}}"
      owner: "{{uid}}"
      mode: "740"
      state: directory
     loop: ["{{prometheus_config_dir}}","{{prometheus_data_dir}}"]
   - name: create User Prometheus
     ansible.builtin.user:
      name: prometheus
      shell: /bin/nologin
      state: absent
      system: true
      uid: "{{uid}}"
  tasks:
   - name: Make sure file config exists
     ansible.builtin.copy:
      src: prometheus-config.yml
      dest: "{{prometheus_config_dir}}/prometheus.yml"
      owner: nobody
      mode: 400
   - name: Deploy Prometheus container
     ansible.builtin.docker_container:
      name: prometheus
      image: prom/prometheus:v3.5.0@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
      command: ['--storage.tsdb.retention.time=14d','--config.file=/etc/prometheus/prometheus.yml']
      
      memory: 128M
      cpus: 0.5
      state: started
      restart_policy: always
      user: "{{uid}}"
      volumes:
        - "{{prometheus_data_dir}}:/prometheus"
        - "{{prometheus_config_dir}}:/etc/prometheus:ro"
      networks:
        - name: runtime-network
          ipv4_address: "192.168.30.4"