#Docs: 
- name: Manage Influxdb
  hosts: ubuntu-server
  become: yes
  vars:
   influx_uid: 1500  #default influx container use this id
   influx_data_container_path: /var/lib/influxdb3/data
   influx_plugins_container_path: /var/lib/influxdb3/plugins
  tasks:
   - name: Make sure directory exists
     ansible.builtin.file:
      state: directory
      mode: "700"
      owner: "{{influx_uid}}"
      group: "{{influx_uid}}"
      recurse: true
      dest: "{{item}}"
     loop: ["/mnt/data1/influxdb3/data","/mnt/data1/influxdb3/plugins"]
   - name: Make sure Influxdb is running
     ansible.builtin.docker_container:
      name: influxdb
      image: influxdb:3.3.0-core@sha256:7ab6964f5a39c436d61c2d7d90a2beef14f7f8637b194e28c650d229ce15bf18
      state: started
      volumes:
       - "/mnt/data1/influxdb3/data:{{influx_data_container_path}}"
       - "/mnt/data1/influxdb3/plugins:{{influx_plugins_container_path}}"
      restart_policy: always
      command:
        - influxdb3
        - serve
        - --node-id=node0
        - --object-store=file
        - --data-dir={{influx_data_container_path}}
        - --plugin-dir={{influx_plugins_container_path}}
      network_mode: host
