apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "sealed-secrets"
  namespace: "argocd"
spec:
  project: "default"
  revisionHistoryLimit: 2
  syncPolicy:
    syncOptions:
    - "ServerSideApply=true"
    automated:
      enabled: true
      selfHeal: true
      prune: true
  destination:
    name: "in-cluster"
    namespace: "sealed-secrets"
  sources:
  - repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: "2.17.2"
    chart: "sealed-secrets"
    helm:
      valueFiles:
      - "$config/k3s/argocd/argocd-app/stateless/sealed-secrets/values.yaml"
  - repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    ref: "config"
