global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'node_exporter'
  static_configs:
  - targets: [ 'localhost:9100' ]

- job_name: 'cadvisori'
  static_configs:
  - targets: [ 'localhost:8080' ]
- job_name: 'traefik'
  metrics_path: /metrics
  static_configs:
  - targets: [ '192.168.30.50:8080' ]
- job_name: 'vaultwarden-postgres-exporter'
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: __param_target
  - source_labels: [ __param_target ]
    target_label: instance
  - target_label: __address__
    replacement: 192.168.1.120:5432
  static_configs:
  - targets:
    - 192.168.30.101:9187
- job_name: 'gitlab-postgres-exporter'
  static_configs:
  - targets:
    - 192.168.30.201:9187
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: __param_target
  - source_labels: [ __param_target ]
    target_label: instance
  - target_label: __address__
    replacement: 192.168.1.120:5432
