apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: "postgresql"
  name: vaultwarden
  owner: "vaultwarden"
