apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: postgresql-prod
  namespace: argocd
spec:
  project: "stateful"
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
  destination:
    namespace: "database"
    name: "in-cluster"
  sources:
  - repoURL: "https://cloudnative-pg.github.io/charts"
    targetRevision: "0.25.0"
  - directory:
      recurse: true
    repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    path: "k3s/postgresql"
