apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: postgresql-prod
  namespace: argocd
spec:
  project: "default"
  syncPolicy:
    syncOptions:
    - "ServerSideApply=true"
    - "CreateNamespace=true"
    automated:
      enabled: true
      prune: true
      selfHeal: true
  destination:
    namespace: "database"
    name: "in-cluster"
  sources:
  - repoURL: "https://cloudnative-pg.github.io/charts"
    chart: "cloudnative-pg"
    targetRevision: "0.25.0"
    helm:
      values: |
        metadata:
         annotations:
          argocd.argoproj.io/sync-wave: "0"
  - directory:
      recurse: true
    repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    path: "k3/argocd/argocd-app/stateful/postgresql/raw-manifests"
