apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: vaultwarden-prod
  namespace: argocd
spec:
  project: "default"
  destination:
    namespace: "vaultwarden"
    name: "in-cluster"
  sources:
  - helm:
      valueFiles:
      - "$config/k3s/argocd-app/vaultwarden/values.yaml"
    repoURL: "https://guerzon.github.io/vaultwarden"
    chart: "vaultwarden"
    targetRevision: "0.32.1"
  - repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    ref: "config"
