apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: vaultwarden-prod
  namespace: argocd
spec:
  revisionHistoryLimit: 2
  project: "default"
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
  destination:
    namespace: "vaultwarden"
    name: "in-cluster"
  sources:
  - helm:
      valueFiles:
      - "$config/k3s/argocd/argocd-app/stateless/vaultwarden/helm/values.yaml"
    repoURL: "https://guerzon.github.io/vaultwarden"
    chart: "vaultwarden"
    targetRevision: "0.32.1"
  - repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    ref: "config"
  - repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    path: "k3s/argocd/argocd-app/stateless/vaultwarden/raw-manifests"
