apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: database
spec:
  cluster:
    name: "postgresql"
  name: vaultwarden
  owner: "vaultwarden"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitlab
  namespace: database
spec:
  cluster:
    name: "postgresql"
  name: gitlab
  owner: gitlab
