apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
spec:
  imageName: "ghcr.io/cloudnative-pg/postgresql:16.9"
  # According to requirement of Gitlab
  # https://docs.gitlab.com/install/requirements/#postgresql-tuning
  resources:
    requests:
      memory: 6Gi
    limits:
      memory: 8Gi
  postgresql:
    parameters:
      work_mem: "8MB"
      maintenance_work_mem: "64MB"
      shared_buffers: "2GB"
      statement_timeout: "60"
  managed:
    roles:
    - name: vaultwarden
      ensure: present
      comment: "Role for Vaultwarden"
      login: true
      superuser: false
      passwordSecret:
        name: "vaultwarden-db-secret"
    - name: gitlab
      ensure: present
      comment: "Role for Gitlab"
      login: true
      superuser: false
      passwordSecret:
        name: "gitlab-db-secret"
  instances: 1
  storage:
    size: 30Gi
