apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  imageName: "ghcr.io/cloudnative-pg/postgresql:16.9"
  affinity:
    nodeSelector:
      k3s.io/hostname: "master-node"
  # According to requirement of Gitlab
  # https://docs.gitlab.com/install/requirements/#postgresql-tuning
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 8Gi
  postgresql:
    parameters:
      work_mem: "8MB"
      maintenance_work_mem: "64MB"
      shared_buffers: "2GB"
      statement_timeout: "60"
  managed:
    roles:
    - name: vaultwarden
      ensure: present
      comment: "Role for Vaultwarden"
      login: true
      superuser: false
      passwordSecret:
        name: "vaultwarden-db"
    - name: gitlab
      ensure: present
      comment: "Role for Gitlab"
      login: true
      superuser: false
      passwordSecret:
        name: gitlab-db
    - name: nextcloud
      comment: Role for nextcloud
      login: true
      superuser: false
      ensure: present
      passwordSecret:
        name: nextcloud-db
  instances: 1
  storage:
    size: 60Gi
    storageClass: "local-path"
