apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: "default"
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: false
  destination:
    namespace: "database"
    name: "in-cluster"
  source:
    directory:
      recurse: false
    repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    path: "k3s/qbittorrent"
