# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box         = "clincha/proxmox-ve-8"
  config.vm.box_version = "1.2.1"

  config.vm.provider "virtualbox" do |vb|
  vb.memory = 20*1024
  vb.cpus = 6
  vb.gui = false
  end
  config.vm.hostname = "pve.local"
  config.vm.network "public_network", bridge: "eno1", auto_config: false
end
