- name: Make sure Prometheus is installed
  hosts: akira-home
  become: yes
  roles:
   - name: prometheus.prometheus.prometheus
     vars: 
      prometheus_config_file: prometheus.yml
  tasks:
    - name: Enable startup
      tags: enabled
      ansible.builtin.service:
       name: prometheus
       enabled: true
       state: started