apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: "default"
  destination:
    namespace: "vaultwarden"
    name: "in-cluster"
  source:
    helm:
      valueFiles:
      - "values.yaml"
    repoURL: "https://guerzon.github.io/vaultwarden"
    chart: "vaultwarden"
    targetRevision: "datnvm/argocd-dev"
    path: "k3s/argocd-app/vaultwarden"
