apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  #docs: https://github.com/k3s-io/k3s-charts/blob/main/charts/traefik/34.2.1%2Bup34.2.0/values.yaml
  valuesContent: |-
    ports:
     web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    persistence:
      # -- Enable persistence using Persistent Volume Claims
      # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
      # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
      enabled: true
      name: data
      existingClaim: ""
      accessMode: ReadWriteMany
      size: 256Mi
      storageClass: "longhorn"
      volumeName: ""
      path: /data
      annotations: {}
      # -- Only mount a subpath of the Volume into the pod
      subPath: ""
    envFrom:
      - secretRef:
          name: traefik-secret
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.email=ngovuminhdat@gmai.com
      - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
