---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    CF_API_EMAIL: AgAzQmx/qlOJCcUU5trWJ166KTNMp81/uIGGhsAZFQ+Xtw2YuuP9ARFv2Q38KEfpai/4i3U6kkrMbf369XEA55hz/ow+MU/NjEv5K9Eranw2Hyqr666oYKKg18ir4KKf1/SwsZgj31mAmZhSvqXRQIRwQNjzXuF8/trmGnIqvqW/Aw+gVNdaCLoQ2wKayBOKeeW1Kwy2tgPHJ4NpSZb3+vT5irkR2unuzWRjZJw83L9ufdRGdhsNVv06tfYlzcKKXqWLtyf3kis146nsqIgeeOyF/8nVV++rq7TfZEzQoEL8N7qPcKBTwDfj1a3VJkeQM+Cf3K0HSojjui6ZX3KOgL6ikuUmEw5P9bDoQctjyENkhQ/bxGqkCkKBq7xbruqXnUfuacZ4+hvsZFAVMTS2FhlNex+k4VTh5oGmXxspey569RZzkmQhwWekxWvnpA1mUIqIynDXhB0CTQLj8nf81NXJTerySWH2mHSKY9xCso1wL64squ0qZ/vIbknTSxYJjFUXVt2g4HXMt1/0JEsPquUYtYntzeOWXTeoy/cuQKLPH/KBU+AbxBqiSXh5dMYCJHy4Z6SgHXhplA73ymZ5imThzW3y32EdYV8iQVJloFJZNlsBoQTxOetZUALaLaXUzrrjBKlktzIfjINLlOsv7iG8C21LpeWknv9DyzxF7K10F0vbE2AnKg4XX7DPlfjtws31+hWlJ6BUL/cXF92C4gyw2Dsb8TWM
    CF_DNS_API_TOKEN: AgDG7HS3PgNDnTNKq8Ig5RTq3T1T4bEWNUXKFg1sDcuAOIziX3CISVK9pZt75dIXFzGULjboRHtKkxN72WJgMb6ON6mGr7LaYOy/qkH5WvzF1A2hhjxp53YORZL0w+wgcRYh2YdwlLYD0uGH1w4IFZKUzv8cxXE93FbhSZ4SMtR6XFcoCvEeiXGFJi5gR4QKM8IPVtFI+iVs73Our09vYikpfq0tjdpOJSqZDhPUxDD8iAX5KfaA1jwPUU+eqOfnGIxE31g+7jUeeOFYdbhxUQZ4Kx97psfOcRmAS/dWUPO/PBwBfWSHBctaj9kwFTNOyMMOSKct6allQUc7JFlMz+Ba9vUhngNPcSiwP/+WpYtoJwG9WcEdUvkUtYD7vBKoafIakBwNobkvQTkqaUJby30d/qLlYhp1l7meO78eL9Tmy/+uV47Huy/aeGfskVIYqS9h2bDYpCper/kJxcDVJnvzSTHth/pNaEQ09S7myVVKKa9I3pEBfQZzDsqegcMUZZiCGKheFrDJJLpuxFLf3+/bsq6VIGI8El3E24cfg2UYDXi5Z49Zuog7opCnFVCcvzYQEmJkJccUVHNq9DhPPQZkmW2t2Mt7b198HaDOJTxQcV1GwGACj8N5BNKZvu+xHpXP/+ElGQXuspA8vGkLgx1393HHs3LiOoKAIQ9pgCTL/QrsXrSqwGVgcqo+KYWCFriIz9oVSEWx+qpRyTg0Wfq3j8iGtSei8wOZ3fC1MVhhg+9es9LYoryV
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system
    type: Opaque
