---
- name: Make sure all my favorate tools is existed
  hosts: ubuntu-server
  gather_facts: true
  become: true
  vars:
    docker_install_script_url: "https://raw.githubusercontent.com/ngodat0103/common-stuff/refs/heads/main/0-shell/0-Installation/docker-installation.sh"
    docker_install_script_path: "/usr/local/bin/docker-installation.sh"
  pre_tasks:
  - name: Ensure we are on Ubuntu 22.04 (Jammy)
    assert:
      that:
      - ansible_facts['distribution'] == 'Ubuntu'
      - ansible_facts['distribution_version'] is version('22.04', '==')
      fail_msg: "This playbook supports only Ubuntu 22.04."
      success_msg: "Ubuntu 22.04 detected."

  tasks:
  - name: Check if Docker is already installed
    command: docker --version
    register: docker_check
    changed_when: false
    failed_when: false

  - name: Download Docker install script (only if Docker missing)
    get_url:
      url: "{{ docker_install_script_url }}"
      dest: "{{ docker_install_script_path }}"
      mode: "0755"
    when: docker_check.rc != 0

  - name: Run Docker install script (only if Docker missing)
    command: bash "{{ docker_install_script_path }}"
    args:
      # Prevent re-running if docker binary exists after install
      creates: /usr/bin/docker
    when: docker_check.rc != 0

  - name: Show Docker version
    command: docker --version
    register: docker_version
    changed_when: false

  - name: Print Docker version
    debug:
      msg: "{{ docker_version.stdout }}"

  - name: "Make sure my networking tools installed"
    ansible.builtin.apt:
     name:
      - net-tools
      - speedtest-cli
      - acl
      - iptables-persistent
      - bridge-utils
      - nmap
     update_cache: true
     state: present