apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  namespace: "argocd"
  name: "minio-prod"
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
  project: "default"
  destination:
    namespace: "minio"
    name: "in-cluster"
  sources:
  - repoURL: "https://operator.min.io"
    chart: "operator"
    targetRevision: "7.1.1"
  - repoURL: "https://operator.min.io"
    chart: "tenant"
    helm:
      valueFiles:
      - "$config/k3s/argocd-app/minio/values.yaml"
    targetRevision: "7.1.1"
  - repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    ref: "config"
