import os

from dotenv import load_dotenv

S3_BUCKET= os.getenv("S3_BUCKET")
S3_ENDPOINT = os.getenv("S3_ENDPOINT")
AWS_REGION = os.getenv("AWS_REGION")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

VAULTWARDEN_DB_HOST = os.getenv("VAULTWARDEN_DB_HOST")
VAULTWARDEN_DB_USERNAME = os.getenv("VAULTWARDEN_DB_USERNAME")
VAULTWARDEN_DB_PASSWORD = os.getenv("VAULTWARDEN_DB_PASSWORD")
