- name: Manage kvm iptables
  hosts: akira-home
  become: yes
  tasks:
  - name: Allow network from virtual network created by kvm to access external network using MASQUERADE
    ansible.builtin.iptables:
      chain: POSTROUTING
      state: present
      table: nat
      source: 192.168.100.0/24
      out_interface: enx000ec6c36eb3
      jump: MASQUERADE
  - name: DNAT this port to ssh vm
    ansible.builtin.iptables:
      chain: PREROUTING
      state: present
      table: nat
      protocol: tcp
      destination_port: 8022
      jump: DNAT
      to_destination: "192.168.100.102:22"
  - name: Deny access to Kvm host
    ansible.builtin.iptables:
      chain: INPUT
      state: present
      protocol: all
      source: "192.168.100.0/24"
      destination: "192.168.1.120/32"
      jump: DROP
  - name: Don't allow access my service docker network2
    ansible.builtin.iptables:
      chain: FORWARD
      state: present
      rule_num: 1
      action: insert
      protocol: all
      source: "192.168.100.0/24"
      destination: "192.168.30.0/24"
      jump: DROP

