- name: Manage Network Docker
  hosts: all
  become_user: akira
  tasks:
   - name: Create runtime network
     ansible.builtin.docker_network:
      name: runtime-network
      ipam_config:
        - subnet: 192.168.30.0/24
   - name: Create a labNetwork
     ansible.builtin.docker_network:
      name: labNetwork
      ipam_config:
        - subnet: 192.168.40.0/24