#Docs: 
- name: Manage Influxdb
  hosts: ubuntu-server
  become: yes
  vars:
   influx_uid: 1500  #default influx container use this id
   influx_data_container_path: /var/lib/influxdb2
   influx_config_container_path: /etc/influxdb2
  tasks:
   - name: Make sure directory exists
     ansible.builtin.file:
      state: directory
      mode: "700"
      owner: "{{influx_uid}}"
      group: "{{influx_uid}}"
      recurse: true
      dest: "{{item}}"
     loop: ["/mnt/data2/influxdb2/data","/mnt/data2/influxdb2/config"]
   - name: Make sure Influxdb is running
     vars:
      influxdb_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34313666373664386161356362666665383761386234663737313634316465656434613763636432
          3864663166346334646266383966333434396362613164390a346131653966396232623231663466
          63666530613539326632376435306531383430613263333435323665383764333239353739366633
          3430373333303135320a356536623337366537633964366637616438636363656464373730646638
          6233
     ansible.builtin.docker_container:
      name: influxdb
      image: influxdb:2.7.12@sha256:59fe0181a3b161d36e9ce53001d7e1678762013ab0a284969ec2ebc517b529cc
      state: started
      volumes:
       - "/mnt/data2/influxdb2/data:{{influx_data_container_path}}"
       - "/mnt/data2/influxdb2/config:{{influx_config_container_path}}"
      restart_policy: always
      env:
       DOCKER_INFLUXDB_INIT_MODE: setup
       DOCKER_INFLUXDB_INIT_USERNAME: influxdb
       DOCKER_INFLUXDB_INIT_PASSWORD:  "{{influxdb_password}}"
       DOCKER_INFLUXDB_INIT_ORG: proxmox
       DOCKER_INFLUXDB_INIT_BUCKET: proxmox
      network_mode: host