apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  storageClassName: "longhorn"
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Mi