apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-db-test
spec:
  instances: 1
  postgresql:
    
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
  storage:
    size: 30Gi
