- name: Manage Alloy
  hosts: akira-home
  become: yes
  vars:
      alloy_config: "{{lookup('ansible.builtin.file','files/config.alloy')}}"
      alloy_secret_config: "{{lookup('ansible.builtin.unvault','files/secret.alloy')}}"
  tasks: 
   - name: Render template and store in variable
     ansible.builtin.set_fact:
      rendered_template: "{{lookup('ansible.builtin.template','templates/config.alloy.j2')}}"
   - name: Configure Alloy
     vars:
      alloy_config: "{{rendered_template}}"
     ansible.builtin.include_role:
      name: grafana.grafana.alloy