#Docs: 

- name: Manage prometheus as agent mode
  hosts: akira-home
  become: yes
  vars:
   prometheus_scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: [ 'localhost:9090' ]
    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'localhost:9100' ]
    - job_name: 'cadvisori'
      static_configs:
        - targets: [ 'localhost:8080' ]
    - job_name: 'traefik'
      metrics_path: /metrics
      static_configs:
        - targets: [ '192.168.30.50:8080' ]
  roles: 
   - prometheus.prometheus.prometheus