#Docs: 

- name: Manage prometheus server
  hosts: akira-home
  become: yes
  vars:
   prometheus_scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: [ 'localhost:9090' ]
    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'localhost:9100' ]
    - job_name: 'cadvisori'
      static_configs:
        - targets: [ 'localhost:8080' ]
    - job_name: 'traefik'
      metrics_path: /metrics
      scrape_interval: 1s
      static_configs:
        - targets: [ '192.168.30.50:8080' ]
    - job_name: vaultwarden-postgres-exporter
      static_configs:
        - targets: ['192.168.30.101:9187']
  roles: 
   - prometheus.prometheus.prometheus