apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: "default"
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
  destination:
    namespace: "database"
    name: "in-cluster"
  source:
    directory:
      recurse: true
    repoURL: "https://github.com/ngodat0103/home-lab.git"
    targetRevision: "datnvm/argocd-dev"
    path: "k3s/postgresql"
