- name: Manage qbittorrent
  hosts: ubuntu-server
  tasks:
  - name: Start qbittorrent
    ansible.builtin.docker_container:
      labels:
        com.github.ngodat0103.service: qbittorrent
      name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:5.1.2@sha256:ebfd00848045b30298bcb43627e24bd98ff2bbf584d9b3e62257586de85bcb15
      state: started
      restart_policy: always
      env:
        PUID: "1000"
        PGID: "1000"
      networks:
      - name: runtime-network
        ipv4_address: 192.168.30.10
      volumes:
      - /mnt:/mnt
      - /mnt/data2/docker/torrent_config:/config