- name: Make sure postgresql-16 is installed
  hosts: postgresql-16
  become: yes
  tasks:
  - name: Add postgresql-16 key
    ansible.builtin.apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
      keyring: /etc/apt/keyrings/postgresql.gpg
  - name: Add postgresql-16 repository
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt {{ansible_distribution_release}}-pgdg main"
      state: present
  - name: Install postgresql-16
    ansible.builtin.apt:
      update_cache: true
      package:
      - postgresql-16
      - postgresql-contrib-16
