- name: Manage interfaces
  hosts: postgresql-16
  become: yes
  tasks:
  - name: Make sure to listen only local and runtime network interface
    ansible.builtin.lineinfile:
      dest: "/etc/postgresql/16/main/postgresql.conf"
      regexp: "^listen_addresses"
      line: "listen_addresses = 'localhost,192.168.99.2'"
